# Generated by Django 4.2.1 on 2023-06-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terminals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_label', models.CharField(max_length=50)),
                ('t1', models.IntegerField()),
                ('t2', models.IntegerField()),
                ('t3', models.IntegerField()),
                ('t4', models.IntegerField()),
                ('t5', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
